name: Main


on:
  push:
    branches: [main, debugging-windows-failure]
  pull_request:
    branches: ["**"]
  merge_group:
    types: [checks_requested]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  Build:
    name: ${{ format('{0} {1}', matrix.platform.target, matrix.features)}}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { target: x86_64-pc-windows-msvc, os: windows-latest, test: true }
        include:
          - features: "chains sm-no-wgl sm-angle-builtin"
            platform:
              { target: x86_64-pc-windows-msvc, os: windows-latest, test: true }
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20"
      - name: Install rust
        id: toolchain
        uses: dtolnay/rust-toolchain@1.89.0
        with:
          targets: ${{ matrix.platform.target }}
      - name: Build
        run: |
          cargo build --features "${{ matrix.features }}" --target ${{ matrix.platform.target }}
      - name: Test
        timeout-minutes: 30 # https://github.com/servo/surfman/issues/329
        env:
          SURFMAN_EGL_TRACE: "1"
        run: |
          cargo test --features "${{ matrix.features }}" --target ${{ matrix.platform.target }} -- --nocapture *>&1 | Tee-Object -FilePath test-output.txt
      - name: Upload test output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output.txt
          if-no-files-found: warn

  build_result:
    name: Result
    runs-on: ubuntu-24.04
    needs: ["Build"]
    if: always()
    steps:
      - name: Mark the job as successful
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        run: exit 0
      - name: Mark the job as unsuccessful
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
